format_version: 1

# model params
network_model: "_2dpaenet" # ["_2dpaenet", "_2dpapenet"]
criterion: "l2" #["l2" "l1"]
cpu: False
convolutional_layer_encoding: "xyz" # ["std", "z", "uv", "xyz"]
dilation_rate: 2 # [1, 2, 4]
mode: "train" #["train", "val"] val只有在test验证集的时候用
baseline_only: False
distillation: "e-e" #["e-e", "e-d"]
hidden_layer: 128
mlp: False

# dataset params
# data_folder: "/home/lab404/ssd_1t/dataset/DepthKITTI/kitti_depth/depth"
# data_folder_rgb: "/home/lab404/ssd_1t/dataset/DepthKITTI/kitti_raw"
data_folder: "/root/autodl-tmp/DepthKITTI/kitti_depth/depth"
data_folder_rgb: "/root/autodl-tmp/DepthKITTI/kitti_raw"

data_folder_save: "./submit_test/"
log_directory: "./mylog"
checkpoint: 'bestmodel'
input: 'rgbd'
jitter: 0.1
freeze_backbone: False
batch_size: 2

# train params
seed: 0
workers: 4
epochs: 100
start_epoch: 0
start_epoch_bias: 0
learning_rate: 0.001
weight_decay: 0.000001
not_random_crop: False
random_crop_height: 320
random_crop_width: 1216
val_h: 352
val_w: 1216
lr_scheduler: StepLR #["CosineAnnealingLR", "ReduceLROnPlateau", "StepLR"]
decay_step: 2
decay_rate: 0.9
gpu: '0'
monitor: 'val/rmse'
stop_patience: 5 # early stopping 
SWA: False # SWA
swa_lr: 0.001 # SWA
swa_epoch_start: 10 # SWA

train_stage0: 1
train_stage1: 3

# val params
val: "select" # ["select", "full"]
rank_metric: 'rmse'
evaluate: ''
test: False

# log params
print_freq: 10

resume: ''